### PR TITLE
Explain how to set ACE_ROOT/TAO_ROOT when building TAO from git

### PR DESCRIPTION
**Pull request by okellogg**
Being used to the ACE_wrappers pre-packaged source distro, I was surprised that the git directory organization is different:
* In the ACE_wrappers, ACE_ROOT points to the ACE_wrappers dir
* In the git clone, ACE_ROOT points to the ACE subdir within ACE_TAO

### CODE REVIEW

**Comment by jwillemsen** [comment]
@okellogg Thanks for the improvements!

**Comment by okellogg** [comment]
Sure!
By the way, is Jeff Parsons still around?
I ask because I made a little patch at [bug 3940](http://bugzilla.dre.vanderbilt.edu/show_bug.cgi?id=3940#c4) which is assigned to him.

**Comment by jwillemsen** [comment]
No, he left the DOC group some years ago and recently retired

**Comment by okellogg** [comment]
Okay...
In general, Is the [DRE Bugzilla](http://bugzilla.dre.vanderbilt.edu) still being maintained?
I ask because of the potential overlap with the [Issues](https://github.com/DOCGroup/ACE_TAO/issues) here.

**Comment by jwillemsen** [comment]
We keep the bugzilla running but are using more and more github issues because of the easy integration with commits

**Comment by okellogg** [comment]
Fine, I'll make a pull request here soon.

**Pull request merged**
