### PR TITLE
support subclassing ACE_Stream

### PR DESCRIPTION
**Pull request by esohns**
this makes some 'private' members 'protected'

### CODE REVIEW

**Comment by esohns** [comment]
please mind only commit [6b2917e](https://github.com/DOCGroup/ACE_TAO/pull/1780/commits/6b2917e77563057a5f89d53df73df06e415b3c81)

**Comment by jwillemsen** [comment]
Reduce this PR only to the change listed in the title

**Comment by esohns** [comment]
OK; please re-review

**Comment by jwillemsen** [comment]
This reverts the changes I made today, please create new branches from master and only apply the single change

**Review by jwillemsen — CHANGES_REQUESTED** [review]
Please recreate with only the real change

**Pull request merged**
