### PR TITLE
Fixed a race condition caused by the double checked locking pattern

### PR DESCRIPTION
**Pull request by nfrmtkr**
Fixed a race condition caused by the double checked locking pattern by using an std::atomic that ensures correct and deterministic create and assignment logic.
Issue #2163

### CODE REVIEW

**Comment by jwillemsen** [comment]
Please also open a PR with the unit test extension as reprocuder

**Comment by nfrmtkr** [comment]
The test Future_Test.cpp will test this from functional point of view. 
The issue can't be easily reproduced. It requires fast machines and it depends on the CPU and compiler being used.

**Comment by nfrmtkr** [comment]
Added new test "Future_Stress_Test"

**Comment by jwillemsen** [comment]
Thanks!

**Pull request merged**
