### PR TITLE
ACE_HAS_GCC_ATOMIC_BUILTINS should be defined for clang

### PR DESCRIPTION
**Pull request by Zaffy**
Making pull request upon request.  
More info can be found on [mailing lists](http://list.isis.vanderbilt.edu/pipermail/ace-bugs/2017-January/000032.html).

### CODE REVIEW

**Comment by jwillemsen** [comment]
Do you know which clang version did introduce the necessary support? For gcc we have this define dependent on the g++ version, probably something similar is necessary for clang.

**Comment by Zaffy** [comment]
Honestly I don't, sorry.

But clang should be highly compatible with gcc so if the checks pass and the macro gets defined then it probably should stay defined.

I don't know what was the original reason for add such code that forcibly undefines it for clang but even if it was legit, it was back in 2010 and clang did a huge step in development.

**Comment by jwillemsen** [comment]
Could you merge master into your branch and push again? I have enable clang on travis-ci as basic test to see if removing this define doesn't break basic support.

**Comment by jwillemsen** [comment]
Thanks!

**Comment by Zaffy** [comment]
Thank You, too! :+1:

**Pull request merged**
