### PR TITLE
Change ACE_Barrier running_threads_ to atomic to ensure accurate values across cores/CPUs

### PR DESCRIPTION
**Pull request by shuston**
Customer experiences ACE_Barrier that (intermittently) never counts down to 1 under heavy system load. Theorizing that the ACE_Sub_Barrier running_threads_ member needs to be atomic to properly be viewed/manipulated across cores/CPUs.

### CODE REVIEW

**Comment by shuston** [comment]
@jwillemsen all the Windows tasks fail... do you know if that's "normal"?

**Comment by jwillemsen** [comment]
I think that is a problem with the vcpkg version used in your branch, I would recommend to merge master into your branch, I think that should resolve that compile issue

**Comment by jwillemsen** [comment]
ACE_Barrier does have a guard that is locked always before using `running_threads_`

**Comment by jwillemsen** [comment]
Maybe worth some test extension? Did you hear from your customer whether this change fixes their issue?

**Comment by shuston** [comment]
> ACE_Barrier does have a guard that is locked always before using `running_threads_`

Yes, but we added an ACE_DEBUG inside that lock and 5 threads called wait and the running_threads_ count was 5 in every thread. The problem only occurs under tremendous load. It may take them some time to get the change into QA and run enough load to see if the problem still occurs.

**Pull request merged**
