### PR TITLE
macOS: sizeof long double is different on ARM64

### PR DESCRIPTION
**Pull request by mitza-oci**
https://developer.apple.com/documentation/xcode/writing-arm64-code-for-apple-platforms#Handle-data-types-and-data-alignment-properly

### CODE REVIEW

**Review by jwillemsen — APPROVED** [review]
Looks ok, I don't have a mac so can't test

**Comment by jwillemsen** [comment]
@mitza-oci What about enabling Mergify (see https://docs.mergify.com/commands/backport) to simplify the backporting you have to perform?

**Comment by mitza-oci** [comment]
> @mitza-oci What about enabling Mergify (see https://docs.mergify.com/commands/backport) to simplify the backporting you have to perform?

We could try it.  Merging only takes a minute though, unless there are conflicts.

**Comment by jwillemsen** [comment]
> > @mitza-oci What about enabling Mergify (see https://docs.mergify.com/commands/backport) to simplify the backporting you have to perform?
> 
> We could try it. Merging only takes a minute though, unless there are conflicts.

I have enabled mergify for ACE/TAO and MPC, let us see if that helps. One of the easy things to use is that you can already give the backport command while the PR is being tested, when it is merged the backport PR is automatically created.

**Pull request merged**
