### PR TITLE
Fix INET_Addr reset IPV6 port problem 

### PR DESCRIPTION
**Pull request by huangminghuang**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Looks INET_Addr test is now failing when ipv6 is enabled, see http://scoreboard.ociweb.com/doc_master_hornet_win7-x64_vc14_i1d0o1w1/index.html

```
tests/INET_Addr_Test


Error: INET_Addr_Test FAILED with exit status 1 after Time:0s

auto_run_tests_finished: tests/INET_Addr_Test Time:0s Result:1
Error: (log/INET_Addr_Test.log): IPv6 set failed: before addr.set(1234), addr.type() = 23
Error: (log/INET_Addr_Test.log): ACE_INET_Addr::ACE_INET_Addr: v6.ipv6-test.com: Authoritive: Host not found
Warning: (log/INET_Addr_Test.log): IPv6 name mismatch: ???????????? (?) != ????????
======= Begin Log File
2017-03-29 22:37:35.254@LM_DEBUG@(6068|4000) Starting INET_Addr_Test test at 2017-03-29 22:37:35.254734
2017-03-29 22:37:35.262@LM_ERROR@IPv6 set failed: before addr.set(1234), addr.type() = 23
after addr.set(1234), addr.type() = 2
2017-03-29 22:37:35.408@LM_ERROR@ACE_INET_Addr::ACE_INET_Addr: v6.ipv6-test.com: Authoritive: Host not found
2017-03-29 22:37:35.411@LM_WARNING@IPv6 name mismatch: ???????????? (?) != ????????
2017-03-29 22:37:35.411@LM_DEBUG@IPv6 tests done
2017-03-29 22:37:35.412@LM_DEBUG@Test TAO Use passed
2017-03-29 22:37:35.414@LM_DEBUG@IPv4 1: 198.206.133.14:123
2017-03-29 22:37:35.414@LM_DEBUG@IPv4 2: 65.182.224.39:123
2017-03-29 22:37:35.414@LM_DEBUG@IPv4 3: 128.138.141.172:123
2017-03-29 22:37:35.414@LM_DEBUG@IPv4 4: 184.105.182.7:123
2017-03-29 22:37:35.417@LM_DEBUG@IPv6 1: [::ffff:69.167.160.102]:123
2017-03-29 22:37:35.417@LM_DEBUG@IPv6 2: [::ffff:107.170.29.136]:123
2017-03-29 22:37:35.417@LM_DEBUG@IPv6 3: [::ffff:198.206.133.14]:123
2017-03-29 22:37:35.417@LM_DEBUG@IPv6 4: [::ffff:199.101.100.221]:123
2017-03-29 22:37:35.417@LM_DEBUG@Test Port Assignment passed
2017-03-29 22:37:35.417@LM_DEBUG@(6068|4000) Ending INET_Addr_Test test at 2017-03-29 22:37:35.417820
======= End Log File
```

**Comment by jwillemsen** [comment]
Also new failures in http://acebuilds.riverace.com/charlie/dev/xlc7_debug/index.html, http://acebuilds.riverace.com/gump/dev/acc_debug/index.html, maybe more, haven't checked all builds

**Comment by jwillemsen** [comment]
INET_Addr test failed already in 11 builds today

**Comment by jwillemsen** [comment]
Test still fails on several platforms including IPv6, even after the fix in issue #385

**Comment by jwillemsen** [comment]
@huangminghuang INET_Addr test still fails on AIX

**Comment by huangminghuang** [comment]
It seems to me those builds fail because of no available IPv6 addresses on the machines. In my opinion, the configuration of those builds should be changed to ipv6=0  or use "ACE_USES_IPV4_IPV6_MIGRATION" to detect the availability of IPv6 at runtime.

**Comment by jwillemsen** [comment]
Please contact @shuston to discuss that, he is hosting the AIX builds

**Comment by jwillemsen** [comment]
Also fails in http://scoreboard.ociweb.com/doc_master_hornet_win7-x64_vc14_i1d0o1w1/index.html

**Comment by huangminghuang** [comment]
The failure in http://scoreboard.ociweb.com/doc_master_hornet_win7-x64_vc14_i1d0o1w1/index.html has nothing to do with the fix. From our Jenkins history, it has been failing at least since commit 2b5be0191af6e6844e7c3528180ceb33276aac5a.

**Comment by jwillemsen** [comment]
Have you contacted @shuston related to AIX?

**Comment by huangminghuang** [comment]
Yes, I did contact @shuston for the AIX problem.

**Comment by jwillemsen** [comment]
@huangminghuang @shuston Any update on how to move forward, I still see the runtime errors on the scoreboard

**Comment by huangminghuang** [comment]
For OCI scoreboard, it is the system problem. The machine only has local IPv6 address which prevents any non-local IPv6  traffic. Our system administrator does not have a solution for it yet.

**Comment by jwillemsen** [comment]
The scoreboard still shows error, maybe revert the change so that you can sort out the issue in parallel?

**Comment by shuston** [comment]
I will try to take a look at it today.

-Steve

On Apr 8, 2017, at 3:12 AM, Johnny Willemsen <notifications@github.com<mailto:notifications@github.com>> wrote:


The scoreboard still shows error, maybe revert the change so that you can sort out the issue in parallel?

**Comment by huangminghuang** [comment]
A few background on PR #394 about the inconsistency behaviors on Windows.

We used the getaddrinfo() sample program from MSDN, modified to set hints.ai_family = AF_INET6 and hints.ai_flags= AI_V4MAPPED. "v6.ipv6-test.com" is specified at command line to query the address. Three windows box with WIndows7 Pro, Windows 2012 server and Windows 10 was tested. Both Windows7 and windows 2012 server are virtual machines. 

The results were that windows 7 machine always returned error, windows 2012 server always succeeded and windows 10 machine sometime succeeded and sometimes failed. We used Wireshark to inspect the packets on the wire and it didn't seems to be the problem of DNS server. 

When we changed the hints.ai_flags to AI_V4MAPPED | AI_ALL, all three machines return 0 from the getaddrinfo() call.

**Comment by jwillemsen** [comment]
@huangminghuang Could you prepare a pull request to revert this PR and the attempts to fix it? That way we get a good scoreboard again and at the moment the issue has a complete fix we can get it in? See my comment on #394, that has been reverted because it broke compilation in several windows builds

**Pull request merged**
