### PR TITLE
Implemented ::SSL_CTX_use_certificate_chain_file function

### PR DESCRIPTION
**Pull request by akotulu**
ACE SSL lacked possibility to handle intermediate certificate CA's.

### CODE REVIEW

**Review by jwillemsen — CHANGES_REQUESTED** [review]
Fuzz fails, please fix that

**Comment by akotulu** [comment]
Hey!

Ran the test, but everything seems ok.

```
ako@MacRiG bin % ./fuzz.pl
--------------------Configuration: Fuzz - Level 5--------------------
Running export file check
Running trailing_whitespaces check
Running ACE_Guard check
Running run_test.pl test
Running deprecated macros check
Running PortableServer::RefCountServantBase derivation check
Running _MSC_VER check
Running empty file test
Running non versioned controlled files check
Running DEPENDENCY_FILE test
Running MAKEFILE variable test
Running ACE_INLINE/ASYS_INLINE check
Running $Id$ string check
Running newline check
Running ACE_Thread_Mutex check
Running ACE_SYNCH_MUTEX check
Running tabs check
Running exception specification check
Running NULL usage check
Running inline check
Running math.h test
Running TCHAR test
Running pre.h/post.h test
Running #pragma (push)/(pop) test
Running versioned namespace begin/end test
Running doxygen @file test
Running absolute ACE_wrappers test
Running TRACE test
Running ptr_arith_t check
Running non-bool equality, relational and logical operator check
Running file names check
Running Improper main() declaration check
Running TAO_Local_RefCounted_Object check
Running the OS.h inclusion check
Running check for numeric flags in DAnCE and DDS4CCM
Running the ORB_init() wide character incompatibility check
Running the ACE log categories check

fuzz.pl - 0 error(s), 0 warning(s)
```

**Comment by jwillemsen** [comment]
See the failing check

**Comment by akotulu** [comment]
Hehe, ok. Didn't know you need to open Raw Log to see actual error.
```
2021-06-03T07:51:56.9113418Z Error: ./ACE/ace/SSL/SSL_Context.cpp:772: found trailing whitespace
```
Well these 2 spaces were present before my improvement.

**Review by jwillemsen — APPROVED** [review]

**Comment by jwillemsen** [comment]
Thanks!

**Pull request merged**
