### PR TITLE
Handle system functions that may be defined as macros on some platforms

### PR DESCRIPTION
**Pull request by ops**

### CODE REVIEW

**Comment by jwillemsen** [comment]
AppVeyor shows some error on Windows

**Comment by ops** [comment]
I'll take a look as soon as I'm less busy

**Comment by ops** [comment]
It seems that some Windows systems do not set ACE_LACKS_ASCTIME_R and ACE_LACKS_GMTIME_R

**Comment by jwillemsen** [comment]
I see it, will revert the pull request for the moment

**Comment by jwillemsen** [comment]
Reverted for the moment to keep a stable master

**Pull request merged**
