### PR TITLE
Remove unimplemented ACE_WFMO_Reactor_Handler_Repository::bind declare.

### PR DESCRIPTION
**Pull request by likema**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Instead of removing it, why not provide an implementation for it?

**Comment by likema** [comment]
`ACE_WFMO_Reactor_Handler_Repository` is an "internal" class for `ACE_WFMO_Reactor`, whose method `bind` has not been used by  `ACE_WFMO_Reactor` any more.

**Comment by likema** [comment]
`ACE_WFMO_Reactor_Handler_Repository` is an "internal" class for `ACE_WFMO_Reactor`, whose method `bind` has not been used by  `ACE_WFMO_Reactor` any more.

**Comment by jwillemsen** [comment]
Thanks!

**Pull request merged**
