### PR TITLE
Inline ACE_OS::thr_gettid

### PR DESCRIPTION
**Pull request by iguessthislldo**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Maybe move this operation inline, looks to be very small and would benefit from being inline

**Review by jwillemsen — CHANGES_REQUESTED** [review]
Please move it to the inline file, it is very small

**Review by jwillemsen — APPROVED** [review]

**Comment by jwillemsen** [comment]
@iguessthislldo I moved the function inline, please merge when you are ok with this

**Comment by iguessthislldo** [comment]
Yes, this is fine.

**Pull request merged**
