### PR TITLE
Fix Coverity Issues and Compiler Warnings

### PR DESCRIPTION
**Pull request by iguessthislldo**
Follow up to #840

### CODE REVIEW

**Review by mitza-oci — APPROVED** [review]

**Review by mitza-oci — APPROVED** [review]

**Review by jwillemsen — APPROVED** [review]

**Comment by jwillemsen** [comment]
One warning left, see https://buildlogs.remedy.nl/win_vs2019_opendds_debug/2021_07_11_02_18_Full.html#warning_1

**Comment by iguessthislldo** [comment]
That looks like it would have been there before, but okay.

**Comment by iguessthislldo** [comment]
#1602

**Comment by mitza-oci** [comment]
> 
> 
> That looks like it would have been there before, but okay.

I think it's due to precedence.  The prior code had one more set of parens `(float) ((ev->u.bval == true) ? 1.0 : 0.0)`, the current code applies the cast to first operand of the `?:`.  One more reason why C++ casts are better than C casts.

**Pull request merged**
