### PR TITLE
Remove obsolescent (void) in functions with no parameters

### PR DESCRIPTION
**Pull request by knutpett**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Thanks!

**Comment by knutpett** [comment]
After the merge I got a report that this job failed. Is it a false positive?

https://github.com/knutpett/ACE_TAO/actions/runs/3050290825/jobs/4917235249#step:13:12367

**Comment by jwillemsen** [comment]
Think it is a false positive, on master it is green

**Comment by jwillemsen** [comment]
You didn't update all *.inl files, maybe rerun your script?

**Pull request merged**
