### PR TITLE
make addr_family_ protected so it can be accessed from derived classes

### PR DESCRIPTION
**Pull request by esohns**

### CODE REVIEW

**Comment by jwillemsen** [comment]
Reordering members will lead to reorder warnings on the constructor(s), please use uniform initialization and simplify the constructor accordingly, very likely the reorder will not lead to warnings at that moment

**Review by jwillemsen — CHANGES_REQUESTED** [review]
Will lead to warnings

**Comment by esohns** [comment]
ok

**Comment by esohns** [comment]
sorry.

**Pull request merged**
