### PR TITLE
Remove warnings -Wextra-semi

### PR DESCRIPTION
**Pull request by knutpett**

### CODE REVIEW

**Comment by knutpett** [comment]
@jwillemsen Can you please have a look at my PR?

**Comment by jwillemsen** [comment]
> @jwillemsen Can you please have a look at my PR?

When you want me to have a guaranteed look see https://www.remedy.nl/services/opensource-support.html for our open source support services, no guarantees on github, see https://github.com/DOCGroup/ACE_TAO/wiki/ACE-and-TAO-Commercial-support

**Review by iguessthislldo — APPROVED** [review]
It's a pretty simple PR and looks alright to me. The only question I have is there a CI or scoreboard build we might want to add this flag to?

**Review by jwillemsen — CHANGES_REQUESTED** [review]

**Comment by knutpett** [comment]
I'm a little surprised that CodeFactor found issues on lines that initially was not a part of change. But since the check failed I fixed it.

**Comment by knutpett** [comment]
> It's a pretty simple PR and looks alright to me. The only question I have is there a CI or scoreboard build we might want to add this flag to?

Regarding the scoreboard, is that something that should be fixed in a different PR?

**Pull request merged**
