### PR TITLE
K format specifier for category name.

### PR DESCRIPTION
**Pull request by pwfran**

### CODE REVIEW

**Comment by iguessthislldo** [comment]
You're using actual tabs, which doesn't look right when displayed the standard way (tab=8 spaces) mixed with space indented code. Vim has `softtabstop` for inserting spaces when tab is pressed and I'm assuming other editors have similar functionality.

**Comment by jwillemsen** [comment]
Please also add documentation to ace/Log_Msg.h and extend tests/Log_Msg_Test.cpp that the new format specifier works

**Comment by pwfran** [comment]
> You're using actual tabs, which doesn't look right when displayed the standard way (tab=8 spaces) mixed with space indented code. Vim has `softtabstop` for inserting spaces when tab is pressed and I'm assuming other editors have similar functionality.

Sorry, my mistake - corrected.

**Comment by pwfran** [comment]
> Please also add documentation to ace/Log_Msg.h and extend tests/Log_Msg_Test.cpp that the new format specifier works

Done.

**Comment by pwfran** [comment]
Does anyone know what is the problem with these failed checks ? I have no access to MSVC. Internal compiler errors in Process_Manager.cpp ?

**Comment by jwillemsen** [comment]
Msvc errors have been fixed on master, please merge master in your branch

**Pull request closed without merging**
