### PR TITLE
Add thread safe ACE_MEM_Addr::get_host_addr.

### PR DESCRIPTION
**Pull request by likema**

### CODE REVIEW

**Comment by likema** [comment]
ACE_INET_Addr has a  thread safe `get_host_addr`, but ACE_MEM_Addr does not has one.

**Comment by jwillemsen** [comment]
Maybe you can take the docu of ACE_INET_Addr and use that also here, now the documentation in ACE_MEM_Addr doesn't tell why there are two operations with the same name but different arguments

**Comment by likema** [comment]
OK

**Comment by jwillemsen** [comment]
Thanks!

**Pull request merged**
