### PR TITLE
Redundantly set the l_linger member to appease gcc

### PR DESCRIPTION
**Pull request by ocielliottc**

### CODE REVIEW

**Comment by jwillemsen** [comment]
When looking at the build logs it seems the warnings are still there, looks the warning is on the line with { 0 }

**Comment by ocielliottc** [comment]
Which build logs are you talking about?  In looking at the gcc logs for this branch, I didn't see any warnings relating to this change.  As far as I can tell, it's ready to be merged.

**Comment by jwillemsen** [comment]
See for example the Linux GCC8 build on Azure (https://dev.azure.com/docgroup/ACE_TAO/_build/results?buildId=964), I attached it log here
[log_255_964.zip](https://github.com/DOCGroup/ACE_TAO/files/3325075/log_255_964.zip)

**Comment by ocielliottc** [comment]
Strange.  I do not know what I was looking at before then.  Let me take another look at the code.

**Pull request merged**
